.\" $Id$
.\"
.\" Copyright (C) 2004  Martin Michlmayr <tbm@cyrius.com>
.\" This manual is freely distributable under the terms of the GPL.
.\" It was originally written for Debian GNU/Linux (but may be used
.\" by others).
.\"

.TH MD5ROM 8 "May 2004"

.SH NAME
md5rom \- output the MD5 checksum of a Cobalt's ROM

.SH SYNOPSIS
.B md5rom

.SH DESCRIPTION
.PP
.B md5rom
calculates the MD5 checksum of the data stored in a Cobalt's ROM and
outputs the checksum.

.SH SEE ALSO
.PP
.BR md5sum (1)

.SH FILES
.PP
.IR /usr/share/doc/colo/COBALT.MD5
- MD5 checksums of original Cobalt firmware

.SH AUTHOR
.PP
Peter Horton <pdh@colonel-panic.org>

